import { Schema, model } from "mongoose";

const researchSchema = new Schema(
  {
    user: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    topic: {
      type: String,
      required: true,
      trim: true,
    },

    // Final markdown report generated by AI
    report: {
      type: String,
      default: "",
    },

    // URLs used while generating report
    sources: [
      {
        type: String,
      },
    ],

    // Critic agent evaluation
    feedback: {
      type: String,
      default: "",
    },

    // Confidence score from validator
    confidence: {
      type: Number,
      default: 0,
    },

    // Raw scraped text (useful for debugging / RAG)
    scrapedContent: {
      type: String,
      default: "",
    },

    // Total runtime (seconds)
    runtime: {
      type: Number,
      default: 0,
    },

    status: {
      type: String,
      enum: [
        "queued",
        "searching",
        "reading",
        "rag",
        "writing",
        "critic",
        "completed",
        "failed",
      ],
      default: "queued",
    },
  },
  {
    timestamps: true,
  }
);

export default model("Research", researchSchema);